# Generated by Django 2.2.6 on 2019-10-31 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
